config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'events#index', as: :authenticated_root
  end

  devise_for :users

  get 'likes/new'

  get 'likes/create'

  get 'likes/destroy'

  get 'videos/index'

  get 'videos/show'

  get 'videos/new'

  get 'videos/create'

  get 'videos/destroy'

  get 'events/index'

  get 'events/show'

  get 'events/new'

  get 'events/create'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 # devise_for :users,
 #    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :events, only: [ :index, :show, :new, :create, :edit, :update ] do
    resources :likes, only: [:create, :destroy]
    resources :videos, only:  [ :index, :show, :new, :create, :destroy]
    resources :user_videos, only: [ :index, :new, :create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  has_many :videos, dependent: :destroy
  has_many :user_videos, dependent: :destroy
  has_many :likes, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

protect_from_forgery with: :exception





  def after_sign_in_path_for(resource)
   events_index_path
 end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.where.not(latitude: nil, longitude: nil)

    @markers = @events.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end
  end

  def show
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to events_index_path
    else
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :address, :description, :price)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def after_user_sign_in
    if user_signed_in?
      redirect_to events_index_path
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/events/index.html.erb
<div
  id="map"
  style="width: 100%;
  height: 100vh;"
  data-markers="<%= @markers.to_json %>"
></div>

app/views/events/new.html.erb
<div class="container">

<h2 style="text-align: center; color: white; margin-top: 50px">Add<span style="color: #8332AC;">Event</span></h2>

 <%= simple_form_for @event do |f| %>
  <div class="form-inputs" style="width: 33%; text-align: center; margin-left: 33%">

    <%= f.input :title, placeholder:"title"%>
    <%= f.input :address, placeholder:"address"%>
    <%= f.input :description, placeholder:"description"%>
    <%= f.input :price, placeholder:"price"%>

  </div>
  <div class="form-actions" style="text-align: center;">

    <%= f.button :submit, "Add Event" %>

 <% end %>
  </div>

</div>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div style="background-color: black; height: 100vh">

    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'shared/navbar' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %>
  </div>

  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/likes/new.html.erb
<h1>Likes#new</h1>
<p>Find me in app/views/likes/new.html.erb</p>

app/views/pages/home.html.erb
<%= render "devise/sessions/new" %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
<div class="navbar-wagon">
  <div class="navbar-wagon-map">
    <%= link_to events_index_path, class: "navbar-wagon-item" do %>
    <i class="far fa-map"></i>
    <% end %>
  </div>
  <div class="navbar-wagon-upload">
    <%= link_to videos_new_path, class: "navbar-wagon-item" do %>
    <i class="far fa-stop-circle"></i>
    <% end %>
  </div>
  <div class="navbar-wagon-profile">

    <div class="dropup">
      <button class="fas fa-user" type="button" data-toggle="dropdown" style="color: white; height: 30px;">
        <span class="caret"></span></button>
        <ul class="dropdown-menu">
          <% if user_signed_in? %>
          <li><%= link_to('Dashboard', videos_show_path) %></li>
          <li><%= link_to('Add Event', events_new_path) %></li>
          <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
          <% else %>
           <li><%= link_to('Dashboard', videos_show_path) %></li>
           <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/videos/create.html.erb
<h1>Videos#create</h1>
<p>Find me in app/views/videos/create.html.erb</p>

app/views/videos/destroy.html.erb
<h1>Videos#destroy</h1>
<p>Find me in app/views/videos/destroy.html.erb</p>

app/views/videos/index.html.erb
<h1>Videos#index</h1>
<p>Find me in app/views/videos/index.html.erb</p>

app/views/videos/new.html.erb
<h1>Videos#new</h1>
<p>Find me in app/views/videos/new.html.erb</p>

app/views/videos/show.html.erb
<h1>Videos#show</h1>
<p>Find me in app/views/videos/show.html.erb</p>